/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const VehicleStatus = IDL.Variant({
  'LOST' : IDL.Record({ 'timeReported' : Time, 'reportNote' : IDL.Text }),
  'FOUND' : IDL.Record({
    'finderReport' : IDL.Text,
    'timeReported' : Time,
    'foundBy' : IDL.Principal,
  }),
  'PAWNED' : IDL.Record({ 'timeReported' : Time, 'reportNote' : IDL.Text }),
  'STOLEN' : IDL.Record({ 'timeReported' : Time, 'reportNote' : IDL.Text }),
  'ACTIVE' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Vehicle = IDL.Record({
  'id' : IDL.Text,
  'engineNumber' : IDL.Text,
  'status' : VehicleStatus,
  'model' : IDL.Text,
  'transferCode' : IDL.Opt(IDL.Text),
  'vehiclePhoto' : ExternalBlob,
  'owner' : IDL.Principal,
  'year' : IDL.Nat,
  'chassisNumber' : IDL.Text,
  'brand' : IDL.Text,
  'location' : IDL.Text,
});
export const VehicleCheckStatus = IDL.Record({
  'statusNote' : IDL.Text,
  'vehicle' : Vehicle,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'onboarded' : IDL.Bool,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
  'vehicleId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTransfer' : IDL.Func([IDL.Text], [], []),
  'adminUpdateVehicleStatus' : IDL.Func([IDL.Text, VehicleStatus], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkVehicle' : IDL.Func([IDL.Text], [VehicleCheckStatus], ['query']),
  'completeOnboarding' : IDL.Func([IDL.Text, UserProfile], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getBackendDiagnostics' : IDL.Func(
      [],
      [IDL.Record({ 'time' : Time, 'build' : IDL.Text })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getInviteTokenReport' : IDL.Func(
      [],
      [IDL.Record({ 'totalGenerated' : IDL.Nat, 'totalUsed' : IDL.Nat })],
      ['query'],
    ),
  'getLostVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getRegisteredVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalLostReports' : IDL.Nat,
          'totalPawnedReports' : IDL.Nat,
          'totalVehicles' : IDL.Nat,
          'totalFoundReports' : IDL.Nat,
          'totalStolenReports' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getVehicle' : IDL.Func([IDL.Text], [Vehicle], ['query']),
  'initiateTransfer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'isAllowlistAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOnboardingAllowed' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'markVehicleAsLostStolenOrPawned' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'stolen' : IDL.Null,
          'lost' : IDL.Null,
          'pawned' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'registerVehicle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'reportVehicleFound' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setupPIN' : IDL.Func([IDL.Text], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updatePIN' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const VehicleStatus = IDL.Variant({
    'LOST' : IDL.Record({ 'timeReported' : Time, 'reportNote' : IDL.Text }),
    'FOUND' : IDL.Record({
      'finderReport' : IDL.Text,
      'timeReported' : Time,
      'foundBy' : IDL.Principal,
    }),
    'PAWNED' : IDL.Record({ 'timeReported' : Time, 'reportNote' : IDL.Text }),
    'STOLEN' : IDL.Record({ 'timeReported' : Time, 'reportNote' : IDL.Text }),
    'ACTIVE' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Vehicle = IDL.Record({
    'id' : IDL.Text,
    'engineNumber' : IDL.Text,
    'status' : VehicleStatus,
    'model' : IDL.Text,
    'transferCode' : IDL.Opt(IDL.Text),
    'vehiclePhoto' : ExternalBlob,
    'owner' : IDL.Principal,
    'year' : IDL.Nat,
    'chassisNumber' : IDL.Text,
    'brand' : IDL.Text,
    'location' : IDL.Text,
  });
  const VehicleCheckStatus = IDL.Record({
    'statusNote' : IDL.Text,
    'vehicle' : Vehicle,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'onboarded' : IDL.Bool,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
    'vehicleId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTransfer' : IDL.Func([IDL.Text], [], []),
    'adminUpdateVehicleStatus' : IDL.Func([IDL.Text, VehicleStatus], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkVehicle' : IDL.Func([IDL.Text], [VehicleCheckStatus], ['query']),
    'completeOnboarding' : IDL.Func([IDL.Text, UserProfile], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getBackendDiagnostics' : IDL.Func(
        [],
        [IDL.Record({ 'time' : Time, 'build' : IDL.Text })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getInviteTokenReport' : IDL.Func(
        [],
        [IDL.Record({ 'totalGenerated' : IDL.Nat, 'totalUsed' : IDL.Nat })],
        ['query'],
      ),
    'getLostVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getRegisteredVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalLostReports' : IDL.Nat,
            'totalPawnedReports' : IDL.Nat,
            'totalVehicles' : IDL.Nat,
            'totalFoundReports' : IDL.Nat,
            'totalStolenReports' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getVehicle' : IDL.Func([IDL.Text], [Vehicle], ['query']),
    'initiateTransfer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'isAllowlistAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOnboardingAllowed' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'markVehicleAsLostStolenOrPawned' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'stolen' : IDL.Null,
            'lost' : IDL.Null,
            'pawned' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'registerVehicle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          ExternalBlob,
        ],
        [IDL.Text],
        [],
      ),
    'reportVehicleFound' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setupPIN' : IDL.Func([IDL.Text], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updatePIN' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };