/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Notification {
  'id' : string,
  'read' : boolean,
  'recipient' : Principal,
  'message' : string,
  'timestamp' : Time,
  'vehicleId' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'country' : string,
  'city' : string,
  'fullName' : string,
  'email' : string,
  'onboarded' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : string,
  'engineNumber' : string,
  'status' : VehicleStatus,
  'model' : string,
  'transferCode' : [] | [string],
  'vehiclePhoto' : ExternalBlob,
  'owner' : Principal,
  'year' : bigint,
  'chassisNumber' : string,
  'brand' : string,
  'location' : string,
}
export type VehicleStatus = {
    'LOST' : { 'timeReported' : Time, 'reportNote' : string }
  } |
  {
    'FOUND' : {
      'finderReport' : string,
      'timeReported' : Time,
      'foundBy' : Principal,
    }
  } |
  { 'ACTIVE' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTransfer' : ActorMethod<[string], undefined>,
  'adminUpdateVehicleStatus' : ActorMethod<[string, VehicleStatus], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOnboarding' : ActorMethod<[string, UserProfile], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getInviteTokenReport' : ActorMethod<
    [],
    { 'totalGenerated' : bigint, 'totalUsed' : bigint }
  >,
  'getLostVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getRegisteredVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getSystemStats' : ActorMethod<
    [],
    {
      'totalLostReports' : bigint,
      'totalVehicles' : bigint,
      'totalFoundReports' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getUserVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getVehicle' : ActorMethod<[string], Vehicle>,
  'initiateTransfer' : ActorMethod<[string, string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOnboardingAllowed' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'markVehicleLost' : ActorMethod<[string, string], undefined>,
  'registerVehicle' : ActorMethod<
    [string, string, string, string, bigint, string, ExternalBlob],
    string
  >,
  'reportVehicleFound' : ActorMethod<[string, string], undefined>,
  'setupPIN' : ActorMethod<[string], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updatePIN' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];