/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export type VehicleStatus = {
    __kind__: "LOST";
    LOST: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "FOUND";
    FOUND: {
        finderReport: string;
        timeReported: Time;
        foundBy: Principal;
    };
} | {
    __kind__: "PAWNED";
    PAWNED: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "STOLEN";
    STOLEN: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "ACTIVE";
    ACTIVE: null;
};
export interface VehicleCheckStatus {
    statusNote: string;
    vehicle: Vehicle;
}
export type Time = bigint;
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Notification {
    id: string;
    read: boolean;
    recipient: Principal;
    message: string;
    timestamp: Time;
    vehicleId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Vehicle {
    id: string;
    engineNumber: string;
    status: VehicleStatus;
    model: string;
    transferCode?: string;
    vehiclePhoto: ExternalBlob;
    owner: Principal;
    year: bigint;
    chassisNumber: string;
    brand: string;
    location: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    country: string;
    city: string;
    fullName: string;
    email: string;
    onboarded: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_stolen_lost_pawned {
    stolen = "stolen",
    lost = "lost",
    pawned = "pawned"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptTransfer(transferCode: string): Promise<void>;
    adminUpdateVehicleStatus(vehicleId: string, newStatus: VehicleStatus): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkVehicle(engineNumber: string): Promise<VehicleCheckStatus>;
    completeOnboarding(inviteToken: string, profile: UserProfile): Promise<void>;
    generateInviteCode(): Promise<string>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getBackendDiagnostics(): Promise<{
        time: Time;
        build: string;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getInviteTokenReport(): Promise<{
        totalGenerated: bigint;
        totalUsed: bigint;
    }>;
    getLostVehicles(): Promise<Array<Vehicle>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getRegisteredVehicles(): Promise<Array<Vehicle>>;
    getSystemStats(): Promise<{
        totalLostReports: bigint;
        totalPawnedReports: bigint;
        totalVehicles: bigint;
        totalFoundReports: bigint;
        totalStolenReports: bigint;
        totalUsers: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserVehicles(): Promise<Array<Vehicle>>;
    getVehicle(vehicleId: string): Promise<Vehicle>;
    initiateTransfer(vehicleId: string, pin: string): Promise<string>;
    isAllowlistAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isOnboardingAllowed(): Promise<boolean>;
    markNotificationRead(notificationId: string): Promise<void>;
    markVehicleAsLostStolenOrPawned(vehicleId: string, category: Variant_stolen_lost_pawned, reportNote: string): Promise<void>;
    registerVehicle(engineNumber: string, chassisNumber: string, brand: string, model: string, year: bigint, location: string, vehiclePhoto: ExternalBlob): Promise<string>;
    reportVehicleFound(vehicleId: string, finderReport: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setupPIN(pin: string): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updatePIN(oldPin: string, newPin: string): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Vehicle as _Vehicle, VehicleCheckStatus as _VehicleCheckStatus, VehicleStatus as _VehicleStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptTransfer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTransfer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTransfer(arg0);
            return result;
        }
    }
    async adminUpdateVehicleStatus(arg0: string, arg1: VehicleStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateVehicleStatus(arg0, to_candid_VehicleStatus_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateVehicleStatus(arg0, to_candid_VehicleStatus_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkVehicle(arg0: string): Promise<VehicleCheckStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkVehicle(arg0);
                return from_candid_VehicleCheckStatus_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkVehicle(arg0);
            return from_candid_VehicleCheckStatus_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeOnboarding(arg0: string, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding(arg0, arg1);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getBackendDiagnostics(): Promise<{
        time: Time;
        build: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackendDiagnostics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackendDiagnostics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getInviteTokenReport(): Promise<{
        totalGenerated: bigint;
        totalUsed: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteTokenReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteTokenReport();
            return result;
        }
    }
    async getLostVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLostVehicles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLostVehicles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getRegisteredVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegisteredVehicles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegisteredVehicles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStats(): Promise<{
        totalLostReports: bigint;
        totalPawnedReports: bigint;
        totalVehicles: bigint;
        totalFoundReports: bigint;
        totalStolenReports: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserVehicles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserVehicles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: string): Promise<Vehicle> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_Vehicle_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_Vehicle_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateTransfer(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateTransfer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateTransfer(arg0, arg1);
            return result;
        }
    }
    async isAllowlistAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAllowlistAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAllowlistAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOnboardingAllowed(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOnboardingAllowed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOnboardingAllowed();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async markVehicleAsLostStolenOrPawned(arg0: string, arg1: Variant_stolen_lost_pawned, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markVehicleAsLostStolenOrPawned(arg0, to_candid_variant_n24(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markVehicleAsLostStolenOrPawned(arg0, to_candid_variant_n24(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async registerVehicle(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVehicle(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVehicle(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async reportVehicleFound(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportVehicleFound(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportVehicleFound(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setupPIN(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setupPIN(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupPIN(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePIN(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePIN(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePIN(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_VehicleCheckStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleCheckStatus): Promise<VehicleCheckStatus> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleStatus): VehicleStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_Vehicle_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Promise<Vehicle> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    statusNote: string;
    vehicle: _Vehicle;
}): Promise<{
    statusNote: string;
    vehicle: Vehicle;
}> {
    return {
        statusNote: value.statusNote,
        vehicle: await from_candid_Vehicle_n14(_uploadFile, _downloadFile, value.vehicle)
    };
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    engineNumber: string;
    status: _VehicleStatus;
    model: string;
    transferCode: [] | [string];
    vehiclePhoto: _ExternalBlob;
    owner: Principal;
    year: bigint;
    chassisNumber: string;
    brand: string;
    location: string;
}): Promise<{
    id: string;
    engineNumber: string;
    status: VehicleStatus;
    model: string;
    transferCode?: string;
    vehiclePhoto: ExternalBlob;
    owner: Principal;
    year: bigint;
    chassisNumber: string;
    brand: string;
    location: string;
}> {
    return {
        id: value.id,
        engineNumber: value.engineNumber,
        status: from_candid_VehicleStatus_n16(_uploadFile, _downloadFile, value.status),
        model: value.model,
        transferCode: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.transferCode)),
        vehiclePhoto: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.vehiclePhoto),
        owner: value.owner,
        year: value.year,
        chassisNumber: value.chassisNumber,
        brand: value.brand,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LOST: {
        timeReported: _Time;
        reportNote: string;
    };
} | {
    FOUND: {
        finderReport: string;
        timeReported: _Time;
        foundBy: Principal;
    };
} | {
    PAWNED: {
        timeReported: _Time;
        reportNote: string;
    };
} | {
    STOLEN: {
        timeReported: _Time;
        reportNote: string;
    };
} | {
    ACTIVE: null;
}): {
    __kind__: "LOST";
    LOST: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "FOUND";
    FOUND: {
        finderReport: string;
        timeReported: Time;
        foundBy: Principal;
    };
} | {
    __kind__: "PAWNED";
    PAWNED: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "STOLEN";
    STOLEN: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "ACTIVE";
    ACTIVE: null;
} {
    return "LOST" in value ? {
        __kind__: "LOST",
        LOST: value.LOST
    } : "FOUND" in value ? {
        __kind__: "FOUND",
        FOUND: value.FOUND
    } : "PAWNED" in value ? {
        __kind__: "PAWNED",
        PAWNED: value.PAWNED
    } : "STOLEN" in value ? {
        __kind__: "STOLEN",
        STOLEN: value.STOLEN
    } : "ACTIVE" in value ? {
        __kind__: "ACTIVE",
        ACTIVE: value.ACTIVE
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Promise<Array<Vehicle>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Vehicle_n14(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleStatus): _VehicleStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_stolen_lost_pawned): {
    stolen: null;
} | {
    lost: null;
} | {
    pawned: null;
} {
    return value == Variant_stolen_lost_pawned.stolen ? {
        stolen: null
    } : value == Variant_stolen_lost_pawned.lost ? {
        lost: null
    } : value == Variant_stolen_lost_pawned.pawned ? {
        pawned: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "LOST";
    LOST: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "FOUND";
    FOUND: {
        finderReport: string;
        timeReported: Time;
        foundBy: Principal;
    };
} | {
    __kind__: "PAWNED";
    PAWNED: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "STOLEN";
    STOLEN: {
        timeReported: Time;
        reportNote: string;
    };
} | {
    __kind__: "ACTIVE";
    ACTIVE: null;
}): {
    LOST: {
        timeReported: _Time;
        reportNote: string;
    };
} | {
    FOUND: {
        finderReport: string;
        timeReported: _Time;
        foundBy: Principal;
    };
} | {
    PAWNED: {
        timeReported: _Time;
        reportNote: string;
    };
} | {
    STOLEN: {
        timeReported: _Time;
        reportNote: string;
    };
} | {
    ACTIVE: null;
} {
    return value.__kind__ === "LOST" ? {
        LOST: value.LOST
    } : value.__kind__ === "FOUND" ? {
        FOUND: value.FOUND
    } : value.__kind__ === "PAWNED" ? {
        PAWNED: value.PAWNED
    } : value.__kind__ === "STOLEN" ? {
        STOLEN: value.STOLEN
    } : value.__kind__ === "ACTIVE" ? {
        ACTIVE: value.ACTIVE
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
